<!DOCTYPE html>
<html lang="fr">

<head>

    <title>APE JV Association de parents d'élèves Jules Vernes La Turballe</title>
    <!--pour les accents-->
    <meta charset="utf-8">

    <!--adapté aux tailles des écrans-->
    <!--pour adapter aux tel portable-->
    <!--zoom de départ-->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--icons-->

    <!--<script src="https://kit.fontawesome.com/3507128011.js" crossorigin="anonymous"></script>-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css">
    

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <!-- <link rel="stylesheet" href="assets/front/css/style.css"> -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Athiti&family=Barriecito&family=Dancing+Script&family=Darumadrop+One&family=Fjalla+One&family=Merienda:wght@400;500;600&family=Nunito:wght@200&family=Parisienne&family=Roboto:ital,wght@1,900&family=Source+Sans+Pro:ital,wght@0,200;0,300;0,600;0,700;1,200;1,300;1,400;1,600&family=Yuji+Hentaigana+Akari&display=swap"
        rel="stylesheet">

    <!--bootstrap-->
    <!-- Favicon -->
    <link rel="icon" href="assets/front/images/logo.png" />
    <link rel="icon" type="image/x-icon" href="assets/front/images/logo.png" />


    <!--styles-->
    <link href="assets/front/css/styles.css" rel="stylesheet" />
    
    <!-- Load an icon library to show a hamburger menu (bars) on small screens -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    
</head>

<body>
    <header>
        <div class="header">
            <div class="logo">
                <a href="?page=home"><img src="assets/front/images/logo.png"></a>
                <h1><span class="ape">Ape</span> <span class="j">J</span><span class="v">V</span></h1>
            </div>
            <h2>Association de parents d'élèves Jules Verne La Turballe</h2>
        </div>
        
        <div class="accueil">
            <nav id="nav">
                <div id="navButton">
                    <div class="burger">
                        <svg width="30" height="22" viewBox="0 0 30 22" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M0 2C0 0.895432 0.895432 0 2 0H28C29.1046 0 30 0.895432 30 2C30 3.10457 29.1046 4 28 4H2C0.895432 4 0 3.10457 0 2ZM0 11C0 9.89543 0.895432 9 2 9H28C29.1046 9 30 9.89543 30 11C30 12.1046 29.1046 13 28 13H2C0.895432 13 0 12.1046 0 11ZM2 18C0.895432 18 0 18.8954 0 20C0 21.1046 0.895432 22 2 22H28C29.1046 22 30 21.1046 30 20C30 18.8954 29.1046 18 28 18H2Z" fill="#fff" />
                        </svg>
                    </div>
                    <div class="cross">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M4.2219 1.39341C3.44085 0.612354 2.17452 0.612354 1.39347 1.39341C0.612415 2.17445 0.612415 3.44078 1.39347 4.22183L9.1716 12L1.39341 19.7782C0.612354 20.5592 0.612354 21.8256 1.39341 22.6066C2.17444 23.3877 3.44078 23.3877 4.22182 22.6066L12 14.8284L19.7782 22.6066C20.5593 23.3877 21.8256 23.3877 22.6067 22.6066C23.3877 21.8256 23.3877 20.5592 22.6067 19.7782L14.8285 12L22.6066 4.22184C23.3877 3.44078 23.3877 2.17446 22.6066 1.39341C21.8256 0.612358 20.5592 0.612358 19.7782 1.39341L12 9.17154L4.2219 1.39341Z" fill="#fff" />
                        </svg>
                    </div>
                </div>
                <ul id="navMenu">
                    <li><a href="<?=$base_uri[0] ?>/public/home"class="active">Accueil</a></li>
                    <li><a href="<?=$base_uri[0] ?>/public/ape">Présentation de l'APE</a></li>
                    <li><a href="<?=$base_uri[0] ?>/public/team">Notre équipe</a></li>
                    <li><a href="<?=$base_uri[0] ?>/public/document">Documents</a></li>
                <!--<li><a href="<?=$base_uri[0] ?>/public/order">Commandes</a></li>-->
                    <li><a href="<?=$base_uri[0] ?>/public/contact">Contact</a></li>
                    <li><a href="<?=$base_uri[0] ?>/public/login">Administrateur</a></li>
                <!--<li><a href=a href="<?=$base_uri[0] ?>/public/basket">Mon panier</a></li>-->
                </ul>
            </nav>
        </div>
        
        
    </header>
    
