<main>
    <div class="diary">
        <h2>Nos prochaine dates à retenir</h2>
            <div class="agenda">
                <?php if(isset($data) && !empty($data)): ?>
                <?php foreach($data['events'] as $event):?>
                    <div class="date">
                        <div class="dates">
                            <p><?= $event->getDate()?></p>
                        </div>
                    <div class="comment">
                        <p><?= $event->getName()?></p>
                        <p><?= $event->getAdress()?></p>
                        <p><?= $event->getdescription()?></p>
                    </div>
                    <a class="btn-edit" href="?page=eventEdit">Modifier</a>
                    <input type="button" name="postid" value="<?= $data['event']->getId(); ?>">
                    <input class="btn-delete" type="button" value="Supprimer">
            </div>
               <?php endforeach;?>
               <?php endif; ?>
        </div>
    </div>
</main>