<main>
    <div class="diary">
        <h2>Nos prochaine dates à retenir</h2>
            <div class="agenda">
                <a href="<?=$base_uri[0] ?>/public/admin/eventAdd/">Ajouter un évènement</a>
                <?php if(isset($data) && !empty($data)): ?>
                <?php foreach($data['events'] as $event):?>
                <pre>
                </pre>
                    <div class="date">
                        <div class="dates">
                            <p><?= $event->getDate()?></p>
                        </div>
                    <div class="comment">
                        <p><?= $event->getName()?></p>
                        <p><?= $event->getAdress()?></p>
                        <p><?= $event->getdescription()?></p>
                    </div>
                    <form action="" method="post">
                        <input type="hidden" name="eventid" value="<?= $event->getId(); ?>">
                        <input class="btn-delete" name="deleteEvent" type="submit" value="Supprimer"/>
                    </form>
                    <a class="btn-edit" href="<?=$base_uri[0] ?>/public/admin/eventEdit/<?= $event->getId(); ?>" name="eventid">Modifier</a>
                    
            </div>
               <?php endforeach;?>
               <?php endif; ?>
        </div>
    </div>
</main>