<?php 


?>
<main class="document">
    <div class="documentAdmin">
        <h2>Administrateur</h2>
        <h3>Nos Assemblées Générales</h3>
            <div class="agAdmin">
                <form action="" method="post" enctype="multipart/form-data">
                    <fieldset>
                        <select name='type'>
                            <option value='ag'>AG</option>
                            <option value='divers'>Divers</option>
                        </select>
                        <input type="file" name="url"><br>
                        <input class="btn-submit" name="addDocumentForm" type="submit" value="Valider">
                    </fieldset>
                </form>
            </div>
    </div>
            
        
    <h2>les résumés de nos diférentes réunions</h2>
    <div class="documents">
        <?php if(isset($data) && !empty($data)): ?>
        <div>
            <h3>Les Assemblées générales</h3>
            <?php  foreach ($data['documents'] as $document): ?>
            <?php  if($document->getType() === 'ag'): ?>
            <a download href="<?=$base_uri[0].'/public/assets/front/doc/'.$document->getUrl(); ?>"><?= $document->getUrl(); ?></a>
                <form action="" method="post">
                    <input type="hidden" name="documentid" value="<?= $document->getId(); ?>">
                    <input class="btn-delete" name="deleteDocument" type="submit" value="Supprimer"/>
                </form>
            <?php endif;?>
            <?php endforeach; ?>
        </div>
        <div>
            <h3>Les documents divers</h3>
            <?php  foreach ($data['documents'] as $document): ?>
            <?php  if($document->getType() === 'divers'): ?>
            <a href="<?= $base_uri[0].'/public/assets/front/doc/'.$document->getUrl(); ?>"><?= $document->getUrl(); ?></a>
                <form action="" method="post">
                    <input type="hidden" name="documentid" value="<?= $document->getId(); ?>">
                    <input class="btn-delete" name="deleteDocument" type="submit" value="Supprimer"/>
                </form>
            <?php endif;?>
            <?php endforeach; ?>
        <?php endif; ?>
        </div>
    </div>
</main>