<main>
    <div class="diaryAdmin">
        <h2>Administrateur</h2>
        <h3>Agenda des évènements</h3>
        <div class="agendaAdmin">
            <form action="#" method="post">
                <fieldset>
                    <legend>Évènements</legend>
                    <label>Date</label><br>
                    <input type="text" name="date"><br>
                    <label>Nom</label><br>
                    <input type="text" name="name"><br>
                    <label>Adresse</label><br>
                    <input type="text" name="adress"><br>
                    <label>Description</label><br>
                    <textarea name="description" id="" cols="30" rows="5"></textarea><br>
                    <label>Lien</label>
                    <input type="text" name="voluntary_link"><br>
                    <input class="btn-submit" name= "addEventEdit" type="button" value="Valider">
                    <input  class="btn-edit" name= "addEventEdit" type="button" value="Modifier">
                </fieldset>
            </form>
        </div>
    </div>
</main>