<main class="commandes">
    <h2>Administrateur</h2>
    <h3>Nos ventes</h3>
    <div class="commande">
        <form action="#" method="post">
            <fieldset>
                <legend>Article</legend>
                <label>Images : </label>
                <input type="file" name="img"><br>
                <label>Nom</label>
                <input type="text" name="name"><br>
                <label>Description</label>
                <input type="text" name="description"><br>
                <label>Prix</label>
                <input type="text" name="price"><br>
                <input class="btn-submit" name="addOrderForm" type="submit" value="Valider">
            </fieldset>
        </form>
    </div>
</main>