 <main class="commandes">
    <h2>Administrateur</h2>
    <h3>Nos ventes</h3>
    <?php if(isset($data) && !empty($data)): ?>
    <?php foreach($data['products'] as $product):?>
    <?phpvar_dump($product):?>
        <table>
            <td><img src="<?= $base_uri[0]?>/public/assets/front/images/<?= $product->getImgUrl()?>" alt="<?= $product->getName(); ?>"></td>
            <td><?= $product->getName()?></td>
            <td><?= $product->getDescription()?></td>
            <td><?= $product->getPrice()?>€</td>
        </table>
        <a class="btn-edit" href="<?=$base_uri[0] ?>/public/admin/orderEdit/<?= $product->getId(); ?>" name="productid">Modifier</a>
                        
        <input class="btn-delete" type="delete" value="Supprimer">
        <?php endforeach;?>
        <?php endif; ?>
</main>