 <article>
        <div class="form">
            <?php if (isset($data)) {
            foreach ($data as $value) {
            echo $value;
                                        }
            } ?>
        </div>
        <form class="user" action="" method="post">
            <div class="form-user">
                <input type="email" name="email" class="form" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Entrer adresse mail...">
            </div>
            <div class="form-group">
                <input type="password" name="password" class="form" id="exampleInputPassword" placeholder="Mot de passe">
            </div>
            <div class="form-group">
                <div class="custom-control custom-checkbox small">
                    <input type="checkbox" class="custom-control-input" id="customCheck">
                    <label class="custom-control-label" for="customCheck">Se rappeler de moi</label>
                </div>
            </div>
            <input type="submit" name="loginForm" class="btn btn-primary btn-user btn-block" value="Valider">

            </form>
            <hr>
            <div class="text-center">
                <a class="small" href="forgot-password.html">Mot de passe oublier</a>
            </div>
            <div class="text-center">
                <a href="<?=$base_uri[0] ?>/public/admin/register/">Créer un compte</a>
            </div>
            
        </div>
    </article>

