<main class="accounts">
        <h2>Nos commandes ce mois-ci!</h2>
            <div class="account">
                <?php foreach($data as $user):?>
                <table>
                    <td><?= $user->getName()?></td>
                    <td><?= $user->getFirst_name()?></td>
                    <td><?= $user->getStudent_id()?>€</td>
                    <td><?= $user->getTel()?></td>
                    <td><?= $user->getEmail()?></td>
                </table>
                <input class="btn-edit" type="edit" value="Modifier">
                <input class="btn-delete" type="delete" value="Supprimer">
            </div>   
        <?php endforeach;?>
    </main>