        <fieldset>
            <legend>Votre règlement</legend>
                <div>
                    <input type="radio" id="creditCard" name="drone" value="creditCard" checked />
                    <label for="creditCard">Carte bancaire via le lien suivant</label>
                </div>
                <div>
                    <input type="radio" id="cash" name="drone" value="cash" />
                    <label for="cash">espèce via votre enfant</label>
                </div>
                <div>
                    <input type="radio" id="cheque" name="drone" value="cheque" />
                    <label for="cheque">chèque dans notre boite aux lettres au nom de : APEJV</label>
                </div>
        </fieldset>
            <input class="btn-submit" type="submit" value="Valider la commande">