<article>
    <form id="myFormulaire" method="post">
        <label for="name">Nom :</label><br>
        <input type="text" id="name" name="name" required><br>

        <label for="first_name">Prénom :</label><br>
        <input type="text" id="first_name" name="first_name" required><br>

        <label for="student">Nom de votre enfant :</label><br>
        <input type="text" id="student" name="student" required><br>

  
       <label for="classroom">Classe de votre enfant :</label><br>
            <select id="classroom" name="classroom">
                <option value="tps">TPS</option>
                <option value="ps">PS</option>
                <option value="ms">MS</option>
                <option value='gs'>GS</option>
                <option value='cp'>CP</option>
                <option value='ce1'>CE1</option>
                <option value='ce2'>CE2</option>
                <option value='cm1'>CM1</option>
                <option value='cm2'>CM2</option>
            </select><br>
        <label for="email">Adresse e-mail :</label><br>
        <input type="email" id="email" name="email" required><br>

        <label for="message">Message :</label><br>
        <textarea id="message" name="message" rows="4" required></textarea><br>

        <input type="submit" name="myFormulaire" value="Envoyer"><br>
    </form><br>
    <p>vos coordonnées seront utilisé uniquement pour que l'on puisse vous répondre</p>
</article>
