<article>
    <div class="form">
        <form action="traitement_formulaire.php" method="post">
            <fieldset>
                <legend>Contact</legend>
                <label>Nom</label>
                <input type="text" name="nom"><br>
                <label>Nom de votre enfant</label>
                <input type="text" name="nom"><br>
                <label>Classe de votre enfant</label>
                <select name='type'>
                    <option value='tps'>TPS</option>
                    <option value='ps'>PS</option>
                    <option value='ms'>MS</option>
                    <option value='gs'>GS</option>
                    <option value='cp'>CP</option>
                    <option value='ce1'>CE1</option>
                    <option value='ce2'>CE2</option>
                    <option value='cm1'>CM1</option>
                    <option value='cm2'>CM2</option>
                </select>
                <label>Email:</label>
                <input type="mail" name="nom"><br>
                <label>Objet</label>
                <input type="text" name="nom"><br>
            </fieldset>
            <fieldset>
                <legend>Ma demande</legend>
                <textarea name="mademande" id="" cols="30" rows="10"></textarea><br>
                <label for="langage">vos coordonnées seront utilisé uniquement pour que l'on puisse vous répondre</label>
                <div>
                    <input type="checkbox" name="langage" value="HTML"><label>RGPD</label>
                </div>
                <button type="submit" class="button" name="contactForm">Valider le formulaire</button>
            </fieldset>
        </form>
    </div>
</article>