    <main class="document">
        <h3>les résumés de nos diférentes réunions</h3>
        <div class="documents">
            <?php if(isset($data) && !empty($data)): ?>
            <div>
            <h2>Les Assemblées générales</h2>
                <?php  foreach($data as $document): ?>
                <?php  if($document->getType() === 'ag'): ?>
                <a download href="<?= $document->getUrl(); ?>"><?= $document->getUrl(); ?></a>
                <?php endif;?>
                <?php endforeach; ?>
            </div>
            <div>
                <h2>Les documents divers</h2>
                <?php  foreach($data as $document): ?>
                <?php  if($document->getType() === 'divers'): ?>
                <a href="<?= $document->getUrl(); ?>"><?= $document->getUrl(); ?></a>
                <?php endif;?>
                <?php endforeach; ?>
            
                <?php endif; ?>

             </div>
        </div>
    </main>



    