    <main>
        <div class="video">
            <iframe src="https://www.youtube.com/embed/EqLMNIWBLBE"
                title="YouTube video player" frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                allowfullscreen></iframe>
        </div>
        
        <div class="diary">
            <h2>Nos prochaine dates à retenir</h2>
        </div>
        <div class="agenda">
            <?php foreach($data as $event):?>
                <div class="date">
                    <div class="dates">
                        <p><?= $event->getDate()?></p>
                    </div>
                    <div class="comment">
                        <ul><?= $event->getName()?></ul>
                        <ul><?= $event->getAdress()?></ul>
                        <ul><?= $event->getdescription()?></ul>
                    </div>
                </div>
               <?php endforeach;?>
        </div>
        <!-- Conteneur principal pour le carrousel -->
    <div class="container">
        <!-- Élément carrousel -->
        <div class="carousel">
            <!-- Conteneur interne pour les diapositives -->
            <div class="carousel-inner">
                <!-- Première diapositive -->
                <div class="slide">
                    <!-- Image de la première diapositive -->
                    <img src="assets/front/images/marche-noel-1.jpg"
                        alt="Image 1">
                </div>
                <!-- Deuxième diapositive -->
                <div class="slide">
                    <!-- Image de la deuxième diapositive -->
                    <img src="assets/front/images/maquillage.jpg"
                        alt="Image 2">
                </div>
                <!-- Troisième diapositive -->
                <div class="slide">
                    <!-- Image de la troisième diapositive -->
                    <img src="assets/front/images/tatouage.jpg"
                        alt="Image 3">
                </div>
                <!-- Quatrième diapositive -->
                <div class="slide">
                    <!-- Image de la quatrième diapositive -->
                    <img src="assets/front/images/vide-grenier.jpg"
                        alt="Image 4">
                </div>
                <!-- Cinquième diapositive -->
                <div class="slide">
                    <!-- Image de la cinquième diapositive -->
                    <img src="assets/front/images/gateau-haloween.jpg"
                        alt="Image 5">
                </div>
            </div>
            <!-- Conteneur pour les boutons de navigation -->
            <div class="carousel-controls">
                <!-- Bouton pour passer à la diapositive précédente -->
                <button id="prev">Précédent</button>
                <!-- Bouton pour passer à la diapositive suivante -->
                <button id="next">Suivant</button>
            </div>
            <!-- Conteneur pour les points de navigation -->
            <div class="carousel-dots"></div>
        </div>
    </div>
    </main>