
<main class="container">
    <h2>Connexion</h2>
    <div class="text-center">
        <?php if (isset($data)) {
            foreach ($data as $value) {
            echo $value;
            }
        } ?>
    </div>
    <form class="user" action="" method="post">
        <div class="form-group">
            <input type="email" name="email" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter votre adresse mail...">
        </div>
        <div class="form-group">
            <input type="password" name="password" id="exampleInputPassword" placeholder="mot de passe">
        </div>
            <input type="submit" name="loginForm" value="Login">
    </form>
    <hr>
    <div class="text-center">
        <a href="<?=$base_uri[0] ?>/public/register/">Créer un compte</a>
    </div>
</main>
 