
    <main class="commandes">
        <h2>Nos commandes ce mois-ci!</h2>
            <div class="commande">
                <?php foreach($data as $product):?>
                <table>
                    <td><img src="<?= $base_uri[0]?>/public/assets/front/images/<?= $product->getImgUrl()?>" alt="<?= $product->getName(); ?>"></td>
                    <td><?= $product->getName()?></td>
                    <td><?= $product->getDescription()?></td>
                    <td><?= $product->getPrice()?>€</td>
                </table>
                <input class="btn-submit" type="submit" value="ajouter">
            </div>   
        <?php endforeach;?>
    </main>