<article>
    <div class="form">
        <form action="#" method="post">
            <fieldset>
                <legend>M'inscrire</legend>
                <label for="name"><abbr title="(required)" aria-hidden="true">*</abbr>Nom :</label>
                <input type="text" id="name" name="name" required><br>
                <label for="firstName"><abbr title="(required)" aria-hidden="true">*</abbr>Prénom :</label>
                <input type="text" id="firstName" name="firstName" required><br>
                <label for="email"><abbr title="(required)" aria-hidden="true">*</abbr>Email :</label>
                <input type="email" id="email" name="email" required><br>
                <label for="password"><abbr title="(required)" aria-hidden="true">*</abbr>Mot de passe :</label>
                <input type="password" id="password" name="password" required><br>
                <input class="btn-submit" name="registerForm" type="submit" value="Valider">
            </fieldset>
        </form>
    </div>
</article>