 <article>
        <div class="form">
            <form action="#" method="post">
                <fieldset>
                    <legend>M'inscrire</legend>
                    <label>Nom</label>
                    <input type="text" name="nom"><br>
                    <label>Prénom</label>
                    <input type="text" name="nom"><br>
                    <label>Nom de votre enfant</label>
                    <input type="text" name="nom"><br>
                    <label>Classe de votre enfant</label>
                    <input type="text" name="nom"><br>
                    <label>Email:</label>
                    <input type="mail" name="nom"><br>
                    <label>Mot de passe</label>
                    <input type="text" name="nom"><br>
                    <input class="btn-submit" type="submit" value="Valider">
                </fieldset>
            </form>
        </div>

    </article>

